### ISSUE TITLE
GFSOD

### ISSUE THREAD

**Issue by Stlve** [er-muyue/DeFRCN#12]
I would like to ask why the AP50 of my run out of GFSOD are 60~70?

**Comment by er-muyue** [comment]
Hi, please let me known the result is conducted on which benchmark (coco or voc), which setting (1shot or 30shot) and which split (split1/2/3). Thank you.
Note that if you use VOC, it is possible. Please review the supplementary material of our [paper](https://arxiv.org/pdf/2108.09017.pdf) (Page 12) or TFA paper-supp (http://proceedings.mlr.press/v119/wang20j/wang20j-supp.pdf) (Page 2).

**Comment by Stlve** [comment]
I did a 3 split on the voc dataset, I did the replication for 1/2/3/5/10 shots, but the tables that came out showed AP50 sizes all 60 to 70, I looked in detail at the data on gfsod in the appendix of the paper, I think the results I came up with for gfsod are the Overall results, is this the correct understanding?

**Comment by er-muyue** [comment]
Yes, I checked my experiment logs and i think it's right. The **Overall AP50** for VOC K-shot (G-FSOD) is about 60 \~ 70, but mAP is will be much lower (about 40\~50). Also you can check _novel AP50_ and _base AP50_ for detailed comparision.

**Comment by Stlve** [comment]
Then I would like to ask if the calculation of mAP in the body of the paper is directly available in the experiment log? I can see from the GFSOD data that the difference between the results of 1/2/3/5/10 shot is still a bit large, what is the exact reason for this?

**Comment by er-muyue** [comment]
A1: Yes, you can get the mAP results directly from the experiment log, which is exactly what we do.
A2: This repo set the λ<sup>GDL-RCNN</sup> for VOC to 0.001 (0.01 in paper) and got better performance, and we had explained this in the [README](https://github.com/er-muyue/DeFRCN/blob/main/README.md). If you get the results (2\~3 points) higher than our paper, I think this is normal. But if the results you get are (much) higher than the results of this repo, please let me know further.

Note: If you are interested in the results in this repo, you can download logs from [GoogleDrive](https://drive.google.com/file/d/1Ff5jP4PCDDPQ7lzsageZsauFWer73QIl/view?usp=sharing).

**Comment by Stlve** [comment]
Thank you very much for your answer to the question I asked.I don't see the mAP data in the test logs, is the mAP the AP in the results.txt file that was output in the experiment?  I am trying to reproduce the results of the COCO paper and I am running the 10/30 shot ,I have been running it for six days on my P100 with two GPU's and it is still not finished, I would like to ask you if it is taking as long as I am to run COCO on your device?

**Comment by er-muyue** [comment]
Sorry for late reply.
A1: yes, the AP in test log is the mAP in paper actually. (follow the definition of [coco_api](https://github.com/cocodataset/cocoapi/tree/master/PythonAPI/pycocotools), and you can check it for more details.)
A2: I use 2080Ti with 8 GPUs in my experiments. For coco, base-training takes 13h, novel-finetuning of 1/2/3/5/10/30-shot take 8min/12min/15min/17min/18min/28min correspondly (single-experiment roughly). See released _logs_ in README for more details.

**Comment by er-muyue** [comment]
Will close this issue for now, but feel free to reopen it if you still have any questions.
