### ISSUE TITLE
If i use my own datasets, the structure of my datasets？

### ISSUE THREAD

**Issue by Williamlizl** [er-muyue/DeFRCN#13]
`  ...
  datasets
    | -- coco (trainval2014/*.jpg, val2014/*.jpg, annotations/*.json)

  ...
`
The structure is ok?

**Comment by er-muyue** [comment]
Hi, I think the structure is ok, but a better way is to add a registration function in this [script](https://github.com/er-muyue/DeFRCN/blob/894747936e57abd3af68f6ff5ce4733d1ba1dd4b/defrcn/data/builtin.py#L95)
