### ISSUE TITLE
cocosplit/datasplit/trainvalno5k

### ISSUE THREAD

**Issue by Williamlizl** [er-muyue/DeFRCN#14]
If I use my own datasets, how to generate the split data?

**Comment by er-muyue** [comment]
The code needs a coco-format annotation file. If you just want to prepare you own datasets for training/testing, you can refer to the coco official [website](https://cocodataset.org/#overview). And if you want to get a few-shot split, you can refer to the code [here](https://github.com/ucbdrive/few-shot-object-detection/tree/master/datasets).

**Comment by Williamlizl** [comment]
> The code needs a coco-format annotation file. If you just want to prepare you own datasets for training/testing, you can refer to the coco official [website](https://cocodataset.org/#overview). And if you want to get a few-shot split, you can refer to the code [here](https://github.com/ucbdrive/few-shot-object-detection/tree/master/datasets).

The split dataset is not necessary?
