### ISSUE TITLE
python tools/extract_results.py Error

### ISSUE THREAD

**Issue by AmingWu** [er-muyue/DeFRCN#15]
Dear Authors,

Thanks for your great work. When I run python tools/extract_results.py, there is an error:

Traceback (most recent call last):
  File "tools/extract_results.py", line 64, in <module>
    main()
  File "tools/extract_results.py", line 39, in main
    results.append([fid] + [float(x) for x in res_info.split(':')[-1].split(',')])
  File "tools/extract_results.py", line 39, in <listcomp>
    results.append([fid] + [float(x) for x in res_info.split(':')[-1].split(',')])
ValueError: could not convert string to float: ' Using a generated random seed 17953176'

Could you give me some advice? Thank you.

**Comment by er-muyue** [comment]
Hi, I think you have modified the format of the output file (maybe this experiment crashed and didn't output anything), please check the log file first and then write a new function to localize the line which has final results according to your output file.
