### ISSUE TITLE
puzzled about learning rate of RPN

### ISSUE THREAD

**Issue by x2ss** [er-muyue/DeFRCN#16]
Dear Authors,

Thanks for your great work.  I have puzzled the learning rate of RPN. 

As stated in the paper, "Moreover, the λ in GDL of RPN is set to 0 for stopping gradient", does it mean that the RPN is never learnt? If the RPN is never learnt, which way is used to initialize it ?

Best!

**Comment by er-muyue** [comment]
'lambda_rpn = 0'：It is not that RPN does not learn but the learning of backbone is not affected by RPN. Note that RPN is updated normally according to the  gradient flow from RPN-head.

**Comment by x2ss** [comment]
Understood! Thanks for your answer!
