### ISSUE TITLE
Results of not using w/G in Table 2

### ISSUE THREAD

**Issue by btbu-saliangbing** [er-muyue/DeFRCN#17]
作者您好！在表2 的结果中，我想问一下对于coco 不使用G-FSOD的结果（9.3，12.9，14.8，16.1，18.5，22.6），是采用FSOD（FSRW-like、TFA-like）的哪一种结果？第一种吗？

**Comment by er-muyue** [comment]
We use the FSRW-like for fair comparision and the TFA-like FSOD results are provided in released logs (see README).
