### ISSUE TITLE
Train and test on my own dataset 

### ISSUE THREAD

**Issue by Loavice** [er-muyue/DeFRCN#21]
Thanks for sharing this great model !

I would like to train your model on my own annotated data. I still there are a few tweaks I need to make here and there, including in DeFRCN/defrcn/data/builtin.py to take into account my data and also in  run_coco.sh. Could you please provide a few guidelines on how I could train your model only once using all my training data and test it on unseen images. 

That would help me a lot (and I guess other people as well).
Any help would be greatly appreciated !

**Comment by er-muyue** [comment]
Hi, i think this repo provides very detailed instructions for custom datasets in the [README](https://github.com/ucbdrive/few-shot-object-detection/blob/master/docs/CUSTOM.md), you can refer to here to modify. Hope that helps!
