### ISSUE TITLE
What if 'RCNN Head' is trainable as well?

### ISSUE THREAD

**Issue by mandal4** [er-muyue/DeFRCN#22]
Nice paper, thanks for releasing your source code.
I got impressed that the cnn backbone is trainable in your theme and make effect.
But what if 'RCNN Head' is trainable as well? 
Have you ever done about it? or is there any reason that you freeze this module?

**Comment by er-muyue** [comment]
In fact, I have did similar experiments before. However, it did not obtain better performance (basically unchanged), and slowed down the training speed. In the novel-finetuning stage, it is not that the more trainable parameters the better. So I chose to freeze the parameters of RCNN-Head. But if you have other ideas, I think it is completely possible to make this part of the parameters trainable. Hope it helps!

**Comment by btbu-saliangbing** [comment]
After the base class is trained, the final classification layer and regression layer of roi head are reinitialized. In the novel-finetuning stage, did you only train them, and the other parameters were frozen? Is this operation consistent with the TFA paper? Thank you！
