### ISSUE TITLE
Whether the PCB is used ？

### ISSUE THREAD

**Issue by btbu-saliangbing** [er-muyue/DeFRCN#23]
Hello, author. I found "_CC.TEST.PCB_ENABLE = False" in "defrcn/config/defaults.py", does it mean that PCB is not used in the inference process ? 
When it is False, "outputs = pcb.execute_calibration(inputs, outputs)" is not executed in "evaluator.py".
Hope to get a reply soon. thanks.

**Comment by er-muyue** [comment]
Hi, please see these yaml files: /path/to/project/configs/coco(or voc)/defrcn_\*_novel_\*.yaml or this [line-example](https://github.com/er-muyue/DeFRCN/blob/894747936e57abd3af68f6ff5ce4733d1ba1dd4b/configs/coco/defrcn_fsod_r101_novel_10shot_seedx.yaml#L30).
Note that the /path/to/project/defrcn/config/defaults.py is not the final version of configuration.
Hope it helps!

**Comment by btbu-saliangbing** [comment]
I get it! Thank you very much!
