### ISSUE TITLE
AssertionError: Checkpoint checkpoints/voc/defrcn/defrcn_det_r101_base3/model_reset_surgery.pth not found

### ISSUE THREAD

**Issue by zhengfang1997** [er-muyue/DeFRCN#25]
i used bash run_voc.sh
 
File "/.../conda_envs/tpami/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint checkpoints/voc/defrcn/defrcn_det_r101_base3/model_reset_surgery.pth not found!

how to solve it? Thx.

`Traceback (most recent call last):
  File "/.../conda_envs/tpami/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/.../conda_envs/tpami/lib/python3.7/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/.../fsod/DeFRCN-main/main.py", line 61, in main
    trainer.resume_or_load(resume=args.resume)
  File "/.../fsod/DeFRCN-main/defrcn/engine/defaults.py", line 290, in resume_or_load
    self.cfg.MODEL.WEIGHTS, resume=resume
  File "/.../conda_envs/tpami/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load
    return self.load(path, checkpointables=[])
  File "/.../conda_envs/tpami/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 153, in load
    assert os.path.isfile(path), "Checkpoint {} not found!".format(path)
AssertionError: Checkpoint checkpoints/voc/defrcn/defrcn_det_r101_base3/model_reset_remove.pth not found!
`

**Comment by zhengfang1997** [comment]
bash run_voc.sh defrcn 3

**Comment by zhengfang1997** [comment]
${SAVE_DIR}/defrcn_det_r101_base${SPLIT_ID}/model_final.pth  not found too

**Comment by alphacyp** [comment]
> i used bash run_voc.sh
> 
> File "/.../conda_envs/tpami/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 153, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint checkpoints/voc/defrcn/defrcn_det_r101_base3/model_reset_surgery.pth not found!
> 
> how to solve it? Thx.
> 
> `Traceback (most recent call last): File "/.../conda_envs/tpami/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap fn(i, *args) File "/.../conda_envs/tpami/lib/python3.7/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker main_func(*args) File "/.../fsod/DeFRCN-main/main.py", line 61, in main trainer.resume_or_load(resume=args.resume) File "/.../fsod/DeFRCN-main/defrcn/engine/defaults.py", line 290, in resume_or_load self.cfg.MODEL.WEIGHTS, resume=resume File "/.../conda_envs/tpami/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 227, in resume_or_load return self.load(path, checkpointables=[]) File "/.../conda_envs/tpami/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 153, in load assert os.path.isfile(path), "Checkpoint {} not found!".format(path) AssertionError: Checkpoint checkpoints/voc/defrcn/defrcn_det_r101_base3/model_reset_remove.pth not found! `
Maybe it's because you didn't put the trained weight file in the correct path

**Comment by er-muyue** [comment]
Hi @zhengfang1997, 
The `model_reset_remove.pth` is generated in this [line](https://github.com/er-muyue/DeFRCN/blob/894747936e57abd3af68f6ff5ce4733d1ba1dd4b/run_voc.sh#L18), please check the base training process is normal or not, and make sure the base model has been properly [trained](https://github.com/er-muyue/DeFRCN/blob/894747936e57abd3af68f6ff5ce4733d1ba1dd4b/run_voc.sh#L13).
