### ISSUE TITLE
Importance of w,w/o FPN in DeFRCN

### ISSUE THREAD

**Issue by buncybunny** [er-muyue/DeFRCN#26]
Hey there! Thanks a lot for the quality codes.

I'm wondering why you guys have taken out FPN from FRCN.
Have you guys done the same experiments with FPN? (wondering if GDL or PCB were afftected by it or all that jazz...)

I couldn't find any details about this in the paper.

**Comment by ssyze** [comment]
@MartinYYYYan I'm sorry that could you share your FPN config file with me? I also add some more Affine layers for the FPN model, but my performance is lower than the RES5ROI model by about 2-5% in any shot. I'm quite confused about this. Thx a lot!

**Comment by er-muyue** [comment]
Hi @buncybunny, I think you have the similary question with this [issue](https://github.com/er-muyue/DeFRCN/issues/5#issuecomment-958726880). Actually, FPN is not a necessary module for verifying the performance of DeFRCN. We directly adopted `Res5ROIHeads` in our paper. If there is enough time next, I will experiment on FPN and provide the experimental results in this repo.
