### ISSUE TITLE
visualization 

### ISSUE THREAD

**Issue by alphacyp** [er-muyue/DeFRCN#27]
Does your code include the visualization program for external input of a single image for detection? If not, can you provide it? Thank you very much.

**Comment by er-muyue** [comment]
Hi, sorry for the late reply.
Unfortunately this repo does not contain any visualization code. If you need it, I think these scripts ([visualize_data](https://github.com/ucbdrive/few-shot-object-detection/blob/master/tools/visualize_data.py) & [visualize_json_results](https://github.com/ucbdrive/few-shot-object-detection/blob/master/tools/visualize_json_results.py)) in TFA can meet your needs.

**Comment by alphacyp** [comment]
> Hi, sorry for the late reply. Unfortunately this repo does not contain any visualization code. If you need it, I think these scripts ([visualize_data](https://github.com/ucbdrive/few-shot-object-detection/blob/master/tools/visualize_data.py) & [visualize_json_results](https://github.com/ucbdrive/few-shot-object-detection/blob/master/tools/visualize_json_results.py)) in TFA can meet your needs.

Thanks for your help！
