### ISSUE TITLE
problem in Running novels

### ISSUE THREAD

**Issue by salehnia** [er-muyue/DeFRCN#28]
Thank you for sharing your code

I used of DeFRCN code (python3.7 and detectron 0.3, cuda 10.2) but I had AP base 12 on my own data, I downloaded pretrain model and replace path into run_coco.sh but I had AP base 12 on my own data and in novels result.txt is empty and i have this Error:
can you help me?

<code>
Traceback (most recent call last):
  File "tools/extract_results.py", line 59, in <module>
    main()
  File "tools/extract_results.py", line 34, in main
    results.append([fid] + [float(x) for x in res_info.split(':')[-1].split(',')])
  File "tools/extract_results.py", line 34, in <listcomp>
    results.append([fid] + [float(x) for x in res_info.split(':')[-1].split(',')])
ValueError: could not convert string to float: " ResNet.make_stage(first_stride=) is deprecated!  Use 'stride_per_block' or 'stride' instead."
</code>

**Comment by salehnia** [comment]
I checked my log.txt file for few-shots and in compare with your log.txt, in my files it just run until this line:
[10/02 15:47:08] d2.data.common INFO: Serializing 130 elements to byte tensors and concatenating them all ...
[10/02 15:47:08] d2.data.common INFO: Serialized dataset takes 0.04 MiB

so it don't start evaluation:
[10/02 15:47:14] defrcn.evaluation.evaluator INFO: Start inference on 625 images

Do you know why this happens? i didn't change evaluation file on your code, and when i run it on COCO too, i have this error.

Thanks

**Comment by er-muyue** [comment]
Hi @salehnia, the `extract_results.py` extracts results from train&eval logs that are trained and tested correctly (just for easy viewing of the benchmark results). If there is an error in this script, I guess that the (base or novel-ft) models are not being trained or tested properly, please check the logs to make sure that the models have been saved and evaluated normally.
If you find any further issues, please let me know. Thanks!

**Comment by salehnia** [comment]
Hi thanks for reply...
I checked log.txt, result on base model are exist, train ans test did correct on it, but in few-shot Novels, evaluation didn't start and last line in log.txt is this:
[01/16 13:43:17] d2.data.common INFO: Serialized dataset takes 0.00 MiB

i have CUDA out of memory, my python version is 3.7, detectron2 -> 0.3 and cuda ->10.2

Thanks
