### ISSUE TITLE
k-shot采样策略

### ISSUE THREAD

**Issue by liliwannian** [er-muyue/DeFRCN#30]
k-shot采样策略分为采样k个包含某一类别的图片和采样k个包含某一类别的标记框，请问这篇文章用的是哪一类方法？

**Comment by er-muyue** [comment]
本文采用和TFA相同的Benchmark。从TFA的数据划分结果统计来看，对于k-shot，会先从该类中采样k张图片，然后从k张图片中采样k个标记框，但这有可能会造成漏标。你可以在TFA的原始数据中（[链接](http://dl.yf.io/fs-det/datasets/)）统计一下进行验证，或者阅读数据[采样代码](https://github.com/ucbdrive/few-shot-object-detection/blob/master/datasets/prepare_coco_few_shot.py)。
