### ISSUE TITLE
could you share the checkpoint files?

### ISSUE THREAD

**Issue by mandal4** [er-muyue/DeFRCN#31]
Thanks for nice paper, nice codes.
I just want to reproduce the experimental result and fine-tuning process.
Could you share the checkpoint files? (both base-training and Fine-tuning)

**Comment by er-muyue** [comment]
Hi, the checkpoints for base training have been uploaded before. Please check the download links of _configs and train logs_ in the README. Considering that there are too many files for the novel finetuning, I'm not going to upload them. If you need, you can directly finetune based on the base weights we provided (it only takes 5 minutes for 1-shot task).
