### ISSUE TITLE
A simple question abount the coco dataset images configuration

### ISSUE THREAD

**Issue by miznchimaki** [er-muyue/DeFRCN#34]
Thanks for your great work! It's a simple yet effective few-shot object detection method!
I have a simple question when I'm building the project dataset:
coco dataset has three sub-directories, respectively called trainval2014, val2014, and annotations. Does the sub-directory trainval2014 mean that this sub-directory contains all training and evaluating images in it? If so, this sub-directory (trainval2014) is used for training, which means the model can see evaluating images information during training. Is this OK?
Hope for your reply sincerely!

**Comment by er-muyue** [comment]
Hi, the images used in the training and testing phases are different, and we define the data split in the [METASPLIT](https://github.com/er-muyue/DeFRCN/blob/894747936e57abd3af68f6ff5ce4733d1ba1dd4b/defrcn/data/builtin.py#L11). You can see the details in this [script](https://github.com/er-muyue/DeFRCN/blob/main/defrcn/data/builtin.py) (from [L12](https://github.com/er-muyue/DeFRCN/blob/894747936e57abd3af68f6ff5ce4733d1ba1dd4b/defrcn/data/builtin.py#L12) \~ [L16](https://github.com/er-muyue/DeFRCN/blob/894747936e57abd3af68f6ff5ce4733d1ba1dd4b/defrcn/data/builtin.py#L16)). 
Thanks!
