### ISSUE TITLE
the code to find the similarity

### ISSUE THREAD

**Issue by liliwannian** [er-muyue/DeFRCN#36]
Hello, first of all, thank you for your work! Where is the code to find the similarity between the images in the support set and the query set? thank you!

**Comment by er-muyue** [comment]
Hi, you can find the PCB module [here](https://github.com/er-muyue/DeFRCN/blob/main/defrcn/evaluation/calibration_layer.py), and this [line](https://github.com/er-muyue/DeFRCN/blob/894747936e57abd3af68f6ff5ce4733d1ba1dd4b/defrcn/evaluation/evaluator.py#L109) executes the calibration operation.
