### ISSUE TITLE
How do I find your core code of GDL and PCB?

### ISSUE THREAD

**Issue by dreamwish1998** [er-muyue/DeFRCN#44]
Great job, how do I find your core code, or where are the major contributions of GDL and PCB code? Thank you so much!

**Comment by sainivedh19pt** [comment]
Hi @weixj1998,

You can find the codebase at defrcn/evaluation/calibration_layer   ----> PrototypicalCalibrationBlock

**Comment by er-muyue** [comment]
@dreamwish1998

**Comment by er-muyue** [comment]
@dreamwish1998 I think you can refer to [GDL](https://github.com/er-muyue/DeFRCN/blob/main/defrcn/modeling/meta_arch/gdl.py) and [PCB](https://github.com/er-muyue/DeFRCN/blob/main/defrcn/evaluation/calibration_layer.py) to access the core code for more details.
