### ISSUE TITLE
RuntimeError: The server socket has failed to listen on any local network address. The server socket has failed to bind to [::]:50153 (errno: 98 - Address already in use). The server socket has failed to bind to ?UNKNOWN? (errno: 98 - Address already in use).

### ISSUE THREAD

**Issue by MALLI7622** [er-muyue/DeFRCN#45]
I am getting this error while running this command
python3 main.py --num-gpus 8 --config-file configs/voc/defrcn_det_r101_base${SPLIT_ID}.yaml     \
    --opts MODEL.WEIGHTS ${IMAGENET_PRETRAIN}                                                   \
           OUTPUT_DIR ${SAVE_DIR}/defrcn_det_r101_base${SPLIT_ID}

**Comment by MALLI7622** [comment]
resolved the error

**Comment by Dhuzi96** [comment]
> 

How to resolve it?
