### ISSUE TITLE
What does 'if final, 10 -> 1 2 3 5 10' in run_voc.sh mean?

### ISSUE THREAD

**Issue by CrapbagMo** [er-muyue/DeFRCN#49]
Hi, thank you for your good work.
When i run FSRW-like fine-tuning in `run_voc.sh` （only line24~line41）, I noticed that after repeat_id 9 and shot 10, my machine went back to repeat_id 0 and shot 1 and started another round of fine-tuning. It doesn't make sense. Does it have anything to with the note 'if final, 10 -> 1 2 3 5 10' in `run_voc.sh`? Would you help me please?

**Comment by er-muyue** [comment]
The public evaluation protocol needs to evaluate 1/2/3/5/10-shot and calculate the average performance, but this usually requires a relatively long experiment time. If it is just to reproduce the experimental results, only run 10-shot to quickly check the environment and experimental results. But for fair & final comparison with our paper, please change 10 to 1/2/3/5/10-shot for full results.

Will close this issue for now, but feel free to reopen it if you still have any questions.
