### ISSUE TITLE
Why TFA links point to cvpods？

### ISSUE THREAD

**Issue by IceHowe** [er-muyue/DeFRCN#50]
In 
"Acknowledgement
This repo is developed based on [TFA](https://github.com/Megvii-BaseDetection/cvpods) and [Detectron2](https://github.com/facebookresearch/detectron2)."

Why TFA links point to cvpods？The TFA is the TFA model(Frustratingly Simple Few-Shot Object Detection) or cvpods？

**Comment by er-muyue** [comment]
Thanks for your kind reminder and I have updated the corresponding link to [TFA](https://github.com/ucbdrive/few-shot-object-detection).
