### ISSUE TITLE
COCO EVAL

### ISSUE THREAD

**Issue by jjxt10** [er-muyue/DeFRCN#53]
When the novel class test set of coco is loaded with 5K JSON why  log.Txt shows that only 625 pictures are loaded
![图片](https://user-images.githubusercontent.com/109153777/178497805-0e4190fd-f2b6-4e25-a728-0d6c0d86877c.png)

**Comment by ZhiXianZ** [comment]
> When the novel class test set of coco is loaded with 5K JSON why log.Txt shows that only 625 pictures are loaded ![图片](https://user-images.githubusercontent.com/109153777/178497805-0e4190fd-f2b6-4e25-a728-0d6c0d86877c.png)

Excuse, have you solved this problem?

**Comment by er-muyue** [comment]
According to your log, I think you used 8 GPU devices during the evaluation, ie. 5000 = 8 * 625.
