### ISSUE TITLE
argument 'alpha' must be Number, not NoneType

### ISSUE THREAD

**Issue by Yxt1212** [er-muyue/DeFRCN#56]
Hello, thanks for your work.
I met a bug: 

d_p = d_p.add(param, alpha=weight_decay)
TypeError: add(): argument 'alpha' must be Number, not NoneType

The detectron2 version is 0.6.Please tell me how could I solve this problem.

**Comment by frostinassiky** [comment]
@Yxt1212 I met the same issue. It is solved by `_CC.SOLVER.WEIGHT_DECAY_BIAS = 0.0 # None` in `defrcn/config/defaults.py`

**Comment by Nahian36** [comment]
> @Yxt1212 I met the same issue. It is solved by `_CC.SOLVER.WEIGHT_DECAY_BIAS = 0.0 # None` in `defrcn/config/defaults.py`

Do I have to add this line, or replace it with any other line?
