### ISSUE TITLE
AssertionError: Checkpoint checkpoints/voc/mydefrcn/defrcn_det_r101_base1/model_reset_remove.pth not found!

### ISSUE THREAD

**Issue by yewanzhuo** [er-muyue/DeFRCN#58]
When I run bash run_voc.sh mydefrcn 1, I get the following error:
AssertionError: Checkpoint checkpoints/voc/mydefrcn/defrcn_det_r101_base1/model_reset_remove.pth not found!. Where can I get model_reset_remove.pth?

**Comment by ZZ2490** [comment]
I also encountered this problem, have you solved it?

**Comment by kobemaker** [comment]
I would like to ask if this file is the result of my own training or provided by the author，model_reset_remove.pth

**Comment by QSJZDDY** [comment]
> 

Have you solve this problem?

**Comment by fky07** [comment]
I met the same question,have you solve it

**Comment by ragini9m** [comment]
I encountered this problem and if you check in the training file you'll see that this file is being created there. You are facing this error because the training file is failing before it can reach that point. Most probably it's a path error.
