### ISSUE TITLE
TypeError: init() got an unexpected keyword argument 'first_stride'

### ISSUE THREAD

**Issue by Decade-Li** [er-muyue/DeFRCN#63]
What is the first_stride parameter set when initializing blocks in the Res5ROIHeads class?
![image](https://user-images.githubusercontent.com/66395799/215498461-f203b962-b408-497f-a93f-723596a7edc0.png)
TypeError: __init__() got an unexpected keyword argument 'first_stride'
Try to solve：
Convert first_stride=2 to stride_per_block=[2, 1, 1]。
![image](https://user-images.githubusercontent.com/66395799/215498944-1e431b93-49e2-4731-b599-60a4747b5e98.png)
But,“TypeError: add(): argument 'alpha' must be Number, not NoneType”.
Then,
![image](https://user-images.githubusercontent.com/66395799/215500651-c38e0e1e-c1b9-491a-9bdb-b79e377f941e.png)
But,"FloatingPointError: Predicted boxes or scores contain Inf/NaN. Training has diverged."

**Comment by fkite-cs** [comment]
Hi, i had the same problem when i was trying to run the model.
If you check the logs in the training examples that they have in google drive, you can find this warning:

![Screenshot from 2023-01-31 10-03-00](https://user-images.githubusercontent.com/47476328/215715590-89692239-215a-429e-8c0f-18a0b6e07e46.png)

To fix this problem i had to modify detectron2 code [https://github.com/facebookresearch/detectron2/blob/58e472e076a5d861fdcf773d9254a3664e045bf8/detectron2/modeling/backbone/resnet.py#L542](url)

Just change "first_stride" key for "stride"
```python
if "first_stride" in list(curr_kwargs.keys()):
    _stride = curr_kwargs["first_stride"]
    del curr_kwargs["first_stride"]
    curr_kwargs["stride"] = _stride
```

**Comment by hairfull** [comment]
I've met the same question, and solve this by degrading detectron2 to v0.3
