### ISSUE TITLE
Why final checkpoint is removed in run_voc.sh script?

### ISSUE THREAD

**Issue by suryasid09** [er-muyue/DeFRCN#67]
Hello @er-muyue,

I have a small doubt, in the novel fine-tuning stage in run_voc.sh script, could you kindly tell why are you removing the model_final.pth file. If you are removed this, you would lose the trained weights. But, still in evaluation you get nice result, how is this possible? I am really confused. Any help from anyone would be really appreciated.

[DeFRCN](https://github.com/er-muyue/DeFRCN)/run_voc.sh
Line number: 38

**Comment by QSJZDDY** [comment]
Have you solve this problem?
