### ISSUE TITLE
where is the `PCB` module？

### ISSUE THREAD

**Issue by Wei-i** [er-muyue/DeFRCN#7]
Hi, I am sorry  that I can not find the code where the `PCB` module for re-weighting the box-predictor' cls scores refers to. 
Hope someone who knows could help me :), thx.

**Comment by er-muyue** [comment]
Hi, you can find the `PCB` module [here](https://github.com/er-muyue/DeFRCN/blob/main/defrcn/evaluation/calibration_layer.py), and this [line](https://github.com/er-muyue/DeFRCN/blob/894747936e57abd3af68f6ff5ce4733d1ba1dd4b/defrcn/evaluation/evaluator.py#L109) executes the calibration operation.

**Comment by Wei-i** [comment]
oh! Thanks a lot!  But this makes me strange because PCB module executes  during `inference`.
When I read your paper, I thought it may be a common module like 'channel wise add' or 'reweighting' during `training`.

**Comment by Wei-i** [comment]
My question is that when we reweight the `score` using PCB module, can we  improve AP?
I think during inference, the input is a image, the output is the list of proposals, each proposal have `score`, `pred labels` and `pred box`.  I am confused that I think coco eval api does not care about the `scores` for a proposal because `label`  and `bbox ` is certain.

**Comment by er-muyue** [comment]
In fact, it does affect. The score represents the confidence of each dt, which will be utilized to re-index dt-bboxes by cocoeval-api (sort dt highest score first, sort gt ignore last). 
Please see these [code](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L259) (or [code](https://github.com/cocodataset/cocoapi/blob/8c9bcc3cf640524c4c20a9c40e89cb6a2f2fa0e9/PythonAPI/pycocotools/cocoeval.py#L173)) in cocoeval-api.

**Comment by Wei-i** [comment]
Thanks you :)
